version: '3.8'

services:
  phi-backend:
    build: .
    container_name: phi-backend-service
    environment:
      # Docker环境的特定配置
      DATABASE_URL: sqlite:/app/data/phigros_bindings.db
      INFO_DATA_PATH: /app/info
      HOST: 0.0.0.0  # 在容器内监听所有接口
      PORT: 8080
      RUST_LOG: info
    volumes:
      # 持久化数据和配置文件
      - ./data:/app/data  # 数据库文件存储
      - ./info:/app/info  # 歌曲信息文件目录
    ports:
      - "8080:8080"  # 宿主机端口:容器端口
    restart: unless-stopped  # 容器异常退出时自动重启

volumes:
  phi-data: # Define the named volume 