name: Build, Release and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  # 任务一：构建和创建发布产物
  build-release:
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    env:
      EXECUTABLE_NAME: phi-backend-rust
      
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
    - name: 恢复Cargo缓存
      uses: Swatinem/rust-cache@v2
    - name: 安装 Rust 工具链
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: ${{ matrix.target }}
    - name: 编译项目
      run: cargo build --release --target ${{ matrix.target }}
    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: phi-backend-${{ matrix.target }}
        # 这里的多行路径写法是正确的，它会尝试上传两个路径，
        # 并优雅地忽略不存在的那个（例如在Linux上忽略.exe）
        path: |
          target/${{ matrix.target }}/release/${{ env.EXECUTABLE_NAME }}
          target/${{ matrix.target }}/release/${{ env.EXECUTABLE_NAME }}.exe

  # 任务二：自动化部署到Linux服务器
  deploy-to-linux-server:
    # 依赖于 build-release 任务，确保编译成功
    needs: build-release
    # 仅在 main 分支的 push 事件时运行此任务
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    env:
      EXECUTABLE_NAME: phi-backend-rust
      PACKAGE_NAME: deploy_package.tar.gz

    steps:
    # 第1步：检出代码，这样我们才能访问到 info 文件夹
    - name: 检出代码
      uses: actions/checkout@v4

    # 第2步：下载编译好的 Linux 可执行文件
    - name: 下载 Linux 构建产物
      uses: actions/download-artifact@v4
      with:
        name: phi-backend-x86_64-unknown-linux-gnu

    # 第3步：打包部署文件
    - name: 创建部署压缩包
      run: |
        # 将可执行文件和 info 文件夹打包到一个 .tar.gz 文件中
        tar -czf ${{ env.PACKAGE_NAME }} ${{ env.EXECUTABLE_NAME }} info/

    # 第4步：安装 SSH Key 并连接服务器进行部署
    - name: 安装 SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder'

    - name: 添加服务器到 known_hosts
      run: ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

    - name: 部署到服务器
      env:
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      run: |
        # 1. 将我们创建的压缩包上传到服务器的家目录
        scp ./${{ env.PACKAGE_NAME }} ${{ env.DEPLOY_USER }}@${{ env.DEPLOY_HOST }}:~/

        # 2. 远程执行服务器上的部署脚本，并将压缩包的路径作为参数传递
        ssh ${{ env.DEPLOY_USER }}@${{ env.DEPLOY_HOST }} "bash /home/ecs-user/deploy_backend.sh ~/${{ env.PACKAGE_NAME }}"