name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.2.3)'
        required: true
      release_type:
        description: 'Release type'
        required: true
        type: choice
        options:
          - 'release'
          - 'prerelease'
        default: 'release'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate version format
        run: |
          if [[ ! "${{ github.event.inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version format. Please use format: X.Y.Z (e.g., 1.2.3)"
            exit 1
          fi

      - name: Update version in Cargo.toml
        run: |
          sed -i "s/version = \".*\"/version = \"${{ github.event.inputs.version }}\"/" Cargo.toml

      - name: Commit version update
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add Cargo.toml
          git commit -m "Update to version ${{ github.event.inputs.version }}"

      - name: Push changes
        run: |
          git push

      - name: Create Git tag
        run: |
          git tag v${{ github.event.inputs.version }}
          git push origin v${{ github.event.inputs.version }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: ${{ github.event.inputs.release_type == 'prerelease' }}